# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

default_twitter: &default_twitter
  twitter_api_key: 'bl2SZXoT5J9LTJ33JfCWEfAhU'
  twitter_api_secret: 'QFAjR4JBOhaBtk9c5MLBRgIz82ayns3MxdsBRVYQGez0lt8k5J'

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0d793c529e3ccb54b0c255569ad21700dbd8519d66b895449b2b4d00caae0502b0591223abe315c6cde6be1c6bbe3de61561879aa69cf0b8e7fd41a7596c7ca
  <<: *default_twitter

test:
  secret_key_base: 134bf8a2b0befb8900e51eb56f313145d9ccb0d9b86b3f9bef150a51eb96b259c55d8239038f5229e8e4ff60d615b2992d9a496aac864a65bd3556c72ac29d14
  <<: *default_twitter

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
